[package]
edition = "2021"
name    = "ass_code"
version = "0.1.0"

[[bin]]
name = "ass_code"
path = "./src/bin/main.rs"

[dependencies]
critical-section = "1.2.0"
embassy-executor = "0.7.0"
embassy-sync = "0.7.0"
embassy-time = "0.4.0"
embedded-graphics = "0.8.1"
embedded-io = "0.6.1"
embedded-storage = "0.3.1"
esp-alloc = { version = "0.6.0" }
esp-backtrace = { version = "0.15.0", features = [
  "esp32s3",
  "exception-handler",
  "panic-handler",
  "println",
] }
esp-hal = { version = "0.23.1", features = ["esp32s3", "unstable"] }
esp-hal-embassy = { version = "0.6.0", features = ["esp32s3"]}
esp-println = { version = "0.13.0", features = ["esp32s3", "log"] }
esp-storage = { version = "0.4.0", features = ["esp32s3"] }
esp-wifi = { version = "0.12.0", default-features = false, features = [
  "esp-alloc",
  "esp32s3",
  "log",
  "utils",
  "wifi",
] }
heapless = { version = "0.8.0", default-features = false }
log = { version = "0.4.21" }
ringbuffer = "0.16.0"
smoltcp = { version = "0.12.0", default-features = false, features = [
  "medium-ethernet",
  "multicast",
  "proto-dhcpv4",
  "proto-dns",
  "proto-ipv4",
  "socket-dns",
  "socket-icmp",
  "socket-raw",
  "socket-tcp",
  "socket-udp",
] }
static_cell = "2.1.0"

[profile.dev]
# Rust debug is too slow.
# For debug builds always builds with some optimization
opt-level = "s"

[profile.release]
codegen-units    = 1     # LLVM can perform better optimizations using a single thread
debug            = 2
debug-assertions = false
incremental      = false
lto              = 'fat'
opt-level        = 's'
overflow-checks  = false
